config/routes.rb
Rails.application.routes.draw do
  root :to => 'categories#index'

  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorie.rb
class Categorie < ActiveRecord::Base
  validates :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Categorie.all
    render :index
  end

  def show
    @categorie= Categorie.find(params[:id])
    render :show
  end

  def new
   @categorie = Categorie.new
   render :new
 end

 def create
    @categorie = Categorie.new(categorie_params)
    if @categorie.save
      redirect_to  categories_path
    else
      render :new
    end
  end

  def edit
      @categorie = Categorie.find(params[:id])
      render :edit
    end

 def update
   @categorie= List.find(params[:id])
   if @categorie.update(categorie_params)
     redirect_to categories_path
   else
     render :edit
   end
 end

private
  def categorie_params
    params.require(:categorie).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<h1>Edit list</h1>

<% if @categorie.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @categorie.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @categorie do |c| %>
  <%= c.select :title, [['Bank'],['Mechanic'],['Store'],['Campground'], ['Pet Store']] %>
  <%= c.submit %>
<% end %>

app/views/categories/index.html.erb
<h1> Categories</h1>

<ul>
  <%@categories.each do |cat| %>
  <li> <%= link_to cat.title, category_path(cat) %> </li>
  <% end %>
</ul>
<%= link_to "New Category", new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<% if @categorie.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @categorie.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @categorie do |c| %>
  <%= c.label :title %>
  <%= c.select :title, [['Bank'],['Mechanic'],['Store'],['Campground'], ['Pet Store']] %>
  <%= c.submit %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @categorie.title %></h1>


<p><%= link_to "Return to Categories", categories_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiPages</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>